// AutolinkedNativeModules.g.cpp contents generated by "npx @react-native-community/cli autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @react-native-clipboard/clipboard
#include <winrt/Clipboard.h>

// Includes from react-native-device-ai
#include <winrt/ReactNativeDeviceAi.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @react-native-clipboard/clipboard
    packageProviders.Append(winrt::Clipboard::ReactPackageProvider());
    // IReactPackageProviders from react-native-device-ai
    packageProviders.Append(winrt::ReactNativeDeviceAi::ReactPackageProvider());
}

}
